# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM node:lts-alpine AS builder
WORKDIR /app
# Install pnpm
RUN npm install -g pnpm
# Copy project files
COPY package.json pnpm-lock.yaml tsconfig.json ./
COPY src ./src
# Install dependencies and build
RUN pnpm install && pnpm run build && pnpm prune --prod

FROM node:lts-alpine
WORKDIR /app
# Copy built artifacts and production deps
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json .

# Expose no ports since stdio
# Default command (overridden by smithery startCommand)
CMD ["node","dist/index.js"]
